export type LabCapabilityKind = "automated" | "manual" | "hybrid";

export type LabCapability = {
  id: string;
  name: string;
  group: string;
  kind: LabCapabilityKind;
  description: string;
  qaIds?: string[];
};

export const ADVANCED_LAB_CAPABILITIES: LabCapability[] = [
  ["test-execution","One-click full test run","execution","hybrid"],["test-execution","Single-feature test run","execution","manual"],["test-execution","Single-test run","execution","manual"],["test-execution","Test suite run","execution","manual"],["test-execution","Failed-tests-only run","execution","hybrid"],["test-execution","Pending-tests-only run","execution","hybrid"],["test-execution","Automated/manual separation","execution","automated"],["test-execution","Test priority levels","execution","manual"],["test-execution","Test severity levels","execution","manual"],["test-execution","Test execution timer","execution","automated"],
["feature-testing","Feature launcher","feature","manual"],["feature-testing","Feature deep-link support","feature","manual"],["feature-testing","Feature-specific workspace","feature","manual"],["feature-testing","Feature prerequisites checker","feature","hybrid"],["feature-testing","Feature health indicator","feature","hybrid"],["feature-testing","Feature coverage percentage","feature","automated"],["feature-testing","Feature readiness status","feature","hybrid"],["feature-testing","Feature dependency map","feature","manual"],["feature-testing","Feature version tracking","feature","manual"],["feature-testing","Feature change detection","feature","manual"],
["automation","Browser capability detection","automation","automated"],["automation","Storage test","automation","automated"],["automation","IndexedDB test","automation","automated"],["automation","Service-worker test","automation","automated"],["automation","PWA test","automation","hybrid"],["automation","Audio test","automation","automated"],["automation","Touch test","automation","automated"],["automation","Keyboard test","automation","hybrid"],["automation","Fullscreen test","automation","automated"],["automation","Network test","automation","automated"],["automation","Online/offline transition test","automation","automated"],["automation","Local persistence test","automation","automated"],["automation","Cache test","automation","hybrid"],["automation","Browser API compatibility test","automation","automated"],["automation","Automated regression suite","automation","hybrid"],
["manual-qa","Step-by-step test instructions","manual-qa","manual"],["manual-qa","Expected-result field","manual-qa","manual"],["manual-qa","Actual-result field","manual-qa","manual"],["manual-qa","PASS / FAIL / BLOCKED / SKIP","manual-qa","manual"],["manual-qa","Tester notes","manual-qa","manual"],["manual-qa","Failure reproduction steps","manual-qa","manual"],["manual-qa","Attach screenshot","manual-qa","manual"],["manual-qa","Attach screen recording","manual-qa","manual"],["manual-qa","Attach console log","manual-qa","hybrid"],["manual-qa","Tester identity","manual-qa","manual"],["manual-qa","Test start/end timestamps","manual-qa","automated"],["manual-qa","Test duration","manual-qa","automated"],["manual-qa","Retest workflow","manual-qa","manual"],["manual-qa","Failure acknowledgement","manual-qa","manual"],["manual-qa","Test confirmation dialog","manual-qa","manual"],
["bugs","Create bug from failed test","bugs","manual"],["bugs","Bug ID generation","bugs","automated"],["bugs","Bug severity","bugs","manual"],["bugs","Bug priority","bugs","manual"],["bugs","Bug status","bugs","manual"],["bugs","Reproduction steps","bugs","manual"],["bugs","Expected vs actual result","bugs","manual"],["bugs","Browser/device information","bugs","automated"],["bugs","Console-error capture","bugs","automated"],["bugs","Network-error capture","bugs","automated"],["bugs","Bug history","bugs","manual"],["bugs","Link bug to test","bugs","manual"],["bugs","Link bug to feature","bugs","manual"],["bugs","Duplicate bug detection","bugs","manual"],["bugs","Regression bug detection","bugs","hybrid"],
["analytics","Pass-rate chart","analytics","automated"],["analytics","Failure-rate chart","analytics","automated"],["analytics","Coverage chart","analytics","automated"],["analytics","Category breakdown","analytics","automated"],["analytics","Feature health matrix","analytics","automated"],["analytics","Test execution timeline","analytics","automated"],["analytics","Failure trend","analytics","automated"],["analytics","Regression trend","analytics","hybrid"],["analytics","Device compatibility matrix","analytics","automated"],["analytics","Browser compatibility matrix","analytics","automated"],["analytics","Network compatibility matrix","analytics","automated"],["analytics","Test-duration analytics","analytics","automated"],["analytics","Most frequently failing tests","analytics","automated"],["analytics","Recently changed tests","analytics","manual"],
["device","Mobile viewport presets","device","automated"],["device","Tablet viewport presets","device","automated"],["device","Desktop viewport presets","device","automated"],["device","Custom viewport","device","automated"],["device","Touch simulation","device","automated"],["device","Orientation testing","device","manual"],["device","Device pixel ratio display","device","automated"],["device","User-agent information","device","automated"],["device","Battery/network information where supported","device","automated"],["device","Responsive-layout screenshots","device","manual"],
["network","Offline simulation","network","manual"],["network","Slow-network simulation","network","manual"],["network","Network recovery test","network","hybrid"],["network","Request failure testing","network","manual"],["network","Cache verification","network","hybrid"],["network","Offline save verification","network","hybrid"],["network","Sync verification","network","manual"],["network","Sync conflict test","network","manual"],["network","Retry-behavior test","network","manual"],["network","Offline/online session report","network","automated"],
].map(([id,name,group,kind], i) => ({
  id: `cap-${String(i + 1).padStart(3, "0")}-${id}`,
  name,
  group,
  kind: kind as LabCapabilityKind,
  description: `${name} capability in the Advanced Test Lab.`,
}));

export const LAB_CAPABILITY_COUNT = ADVANCED_LAB_CAPABILITIES.length;
